### ISSUE TITLE
USER STORY: View saved patterns

### ISSUE THREAD

**Issue by akirby23** [akirby23/the-crochet-corner#12]
As a **registered user**, I can **view my saved crochet patterns** so that **I can easily access the patterns that interest me as and when I need to**.

### Acceptance Criteria
- Only users who have logged in should be able to view their saved patterns. 
- Only patterns that the user has saved should be accessible on the My Saved Patterns page. 
- The patterns saved by the user should be displayed in a clear format on the My Saved Patterns page. 

### Tasks
- [x] Create a template for the My Saved Patterns page.
- [x] Nest the My Saved Patterns page in a dropdown menu in the navigation bar.
- [x] Build the view and URL, wire it up to the template.
