### ISSUE TITLE
USER STORY: Create crochet patterns

### ISSUE THREAD

**Issue by akirby23** [akirby23/the-crochet-corner#13]
As a **site admin**, I can **create new crochet patterns** so that **users can access them**.

### Acceptance Criteria 
- Crochet patterns should be created via a form that is accessible via the admin panel only.
- The form should be intuitive, prompting the site admin to provide important information such as the title, description, difficulty level, recommended yarn type, recommended hook size, gauge & instructions. 
- The site admin should be able to upload an image of the completed crochet project to accompany the pattern.

### Tasks

- [x] Build the Pattern model.
- [x] Import the Pattern model into the admin.py file. 
- [x] Install Summernote. Set the description & instructions text fields to summernote fields.
