### ISSUE TITLE
USER STORY: Delete crochet patterns [Frontend]

### ISSUE THREAD

**Issue by akirby23** [akirby23/the-crochet-corner#29]
As a **registered user**, I can **delete my own crochet patterns** so that **I can maintain my collection**.

### Acceptance Criteria
- Only users who are logged in should be able to delete patterns.
- Users should only be able to delete their own patterns. 

### Tasks
- [x] Create a template to render the pattern deletion form.
- [x] Set up the view & url.
- [x] Add a delete button to the pattern page, make it visible to the user who created the pattern only.
