### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by akirby23** [akirby23/the-crochet-corner#4]
As a **registered user**, I can **sign out** so that **I can ensure the security of my account**.

### Acceptance Criteria
- A "Log Out" button should be visible in the navigation bar to users who are signed in. 
- Feedback should be provided to the user to confirm that they have successfully signed out. 

### Tasks 

- [x] Configure URLs.
- [x] Add the logout URL to the navigation element in the base template.
- [x] Customise the logout.html file.
- [x] Set up alert messages.
