### ISSUE TITLE
USER STORY: Comment on patterns

### ISSUE THREAD

**Issue by akirby23** [akirby23/the-crochet-corner#6]
As a **registered user**, I can **comment on a crochet pattern** so that **I can share thoughts and/or feedback**.

### Acceptance Criteria

- Only users that have logged in should be able to leave a comment. 
- Users who are not logged in should be prompted to log in/sign up before adding a comment. 

### Tasks

- [x] Build the Comment model & views.
- [x] Build the form for comment submission. 
- [x] Write templates for users who are authenticated & for users who are not.
