### ISSUE TITLE
USER STORY: Save patterns for later

### ISSUE THREAD

**Issue by akirby23** [akirby23/the-crochet-corner#7]
As a **registered user**, I can **save or unsave a crochet pattern for later** so that **I can easily access it in the future, or remove it if I no longer need it**.

### Acceptance Criteria
- A bookmark icon labelled "Save for later" should display on each crochet pattern.
- Users should be able to click on the icon to save the pattern for later. 
   - Users who are not signed in should be prompted to log in or sign up if they attempt to save the pattern. 
   - Users who are signed in should be given feedback to confirm whether or not the pattern was successfully saved. 
- Users who are logged in should be able to unsave patterns.

### Tasks
- [x] Add the bookmark icon to the pattern page.
- [x] Add log in/sign up calls to action for users who are not logged in.
- [x] Add functionality to save/unsave patterns.
